# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'test.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(664, 627)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(14)
        Dialog.setFont(font)
        self.btnStart = QtWidgets.QToolButton(Dialog)
        self.btnStart.setGeometry(QtCore.QRect(260, 550, 121, 61))
        self.btnStart.setObjectName("btnStart")
        self.appidTxt = QtWidgets.QTextEdit(Dialog)
        self.appidTxt.setGeometry(QtCore.QRect(260, 90, 371, 31))
        self.appidTxt.setAcceptDrops(True)
        self.appidTxt.setObjectName("appidTxt")
        self.pidTxt = QtWidgets.QTextEdit(Dialog)
        self.pidTxt.setGeometry(QtCore.QRect(260, 140, 371, 31))
        self.pidTxt.setObjectName("pidTxt")
        self.cdnTxt = QtWidgets.QTextEdit(Dialog)
        self.cdnTxt.setGeometry(QtCore.QRect(260, 180, 371, 31))
        self.cdnTxt.setObjectName("cdnTxt")
        self.serverTxt = QtWidgets.QTextEdit(Dialog)
        self.serverTxt.setGeometry(QtCore.QRect(260, 230, 371, 31))
        self.serverTxt.setObjectName("serverTxt")
        self.pageTxt = QtWidgets.QTextEdit(Dialog)
        self.pageTxt.setGeometry(QtCore.QRect(260, 280, 371, 31))
        self.pageTxt.setObjectName("pageTxt")
        self.jiangeTxt = QtWidgets.QTextEdit(Dialog)
        self.jiangeTxt.setGeometry(QtCore.QRect(260, 330, 371, 31))
        self.jiangeTxt.setObjectName("jiangeTxt")
        self.maxPlayerNumTxt = QtWidgets.QTextEdit(Dialog)
        self.maxPlayerNumTxt.setGeometry(QtCore.QRect(260, 380, 371, 31))
        self.maxPlayerNumTxt.setObjectName("maxPlayerNumTxt")
        self.curNumTxt = QtWidgets.QLabel(Dialog)
        self.curNumTxt.setGeometry(QtCore.QRect(260, 420, 101, 41))
        font = QtGui.QFont()
        font.setFamily("仿宋")
        font.setPointSize(14)
        self.curNumTxt.setFont(font)
        self.curNumTxt.setObjectName("curNumTxt")
        self.splitter = QtWidgets.QSplitter(Dialog)
        self.splitter.setGeometry(QtCore.QRect(10, 80, 221, 381))
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName("splitter")
        self.label = QtWidgets.QLabel(self.splitter)
        self.label.setBaseSize(QtCore.QSize(20, 20))
        font = QtGui.QFont()
        font.setFamily("仿宋")
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.splitter)
        self.label_2.setBaseSize(QtCore.QSize(20, 20))
        font = QtGui.QFont()
        font.setFamily("仿宋")
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.splitter)
        self.label_3.setBaseSize(QtCore.QSize(20, 20))
        font = QtGui.QFont()
        font.setFamily("仿宋")
        font.setPointSize(14)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.splitter)
        self.label_4.setBaseSize(QtCore.QSize(20, 20))
        font = QtGui.QFont()
        font.setFamily("仿宋")
        font.setPointSize(14)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.splitter)
        self.label_5.setBaseSize(QtCore.QSize(20, 20))
        font = QtGui.QFont()
        font.setFamily("仿宋")
        font.setPointSize(14)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.splitter)
        self.label_6.setBaseSize(QtCore.QSize(20, 20))
        font = QtGui.QFont()
        font.setFamily("仿宋")
        font.setPointSize(14)
        self.label_6.setFont(font)
        self.label_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.splitter)
        self.label_7.setBaseSize(QtCore.QSize(20, 20))
        font = QtGui.QFont()
        font.setFamily("仿宋")
        font.setPointSize(14)
        self.label_7.setFont(font)
        self.label_7.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.splitter)
        self.label_8.setBaseSize(QtCore.QSize(20, 20))
        font = QtGui.QFont()
        font.setFamily("仿宋")
        font.setPointSize(14)
        self.label_8.setFont(font)
        self.label_8.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_8.setObjectName("label_8")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "传奇AI"))
        self.btnStart.setText(_translate("Dialog", "开始"))
        self.curNumTxt.setText(_translate("Dialog", "0"))
        self.label.setText(_translate("Dialog", "游戏appid"))
        self.label_2.setText(_translate("Dialog", "游戏pid"))
        self.label_3.setText(_translate("Dialog", "cdn地址"))
        self.label_4.setText(_translate("Dialog", "服务器地址"))
        self.label_5.setText(_translate("Dialog", "页数"))
        self.label_6.setText(_translate("Dialog", "生成机器人的间隔"))
        self.label_7.setText(_translate("Dialog", "最大生成人数"))
        self.label_8.setText(_translate("Dialog", "当前机器人数量"))
